### ISSUE TITLE
Add runtime in heroku

### ISSUE THREAD

**Issue by sanketgarade** [mukta-strot/MarathiNotMaharashtrianBot#5]

**Comment by sanketgarade** [comment]
@vinodnimbalkar 

I added you as a collaborator to the muktastrot heroku account. 
Let me know if you have any issues in access or rights/privileges.

I have also given you write access to this repo so you should be able to make direct commits to this repo i guess. 😃

**Comment by vinodnimbalkar** [comment]
I've added runtime.txt file.

**Comment by sanketgarade** [comment]
आभारी आहे! हा issue समाप्त करू का मग?

**Comment by vinodnimbalkar** [comment]
होय.
