### ISSUE TITLE
Detect महाराष्ट्रीयन (in Devanagari)

### ISSUE THREAD

**Issue by sanketgarade** [mukta-strot/MarathiNotMaharashtrianBot#9]
Currently detection only in latin script "Maharashtrian" is enabled.

**Comment by sanketgarade** [comment]
@vinodnimbalkar 

Is change in 4618a32 ok for detecting in Devanagari?

**Comment by vinodnimbalkar** [comment]
Yes, or you can replace the below line with the existing one
`r'^maharashtrian\b|\s\bmaharashtrian\b|\bmaharashtrians|^महाराष्ट्रीयन\s|\sमहाराष्ट्रीयन\s', re.IGNORECASE)`
here we are detecting **महाराष्ट्रीयन** word start of the line as well as checking **महाराष्ट्रीयन** with start/end `space`.

**Comment by sanketgarade** [comment]
कळलं. ते `/b, ^, /s` नक्की काय करतात सांगू शकतो का? किंवा त्यांची मदत कुठे वाचता येईल त्याची दुवा देऊ शकतो का? मी वाचून समजायचा प्रयत्न करतो.

**Comment by sanketgarade** [comment]
```
2022-01-04T06:41:35.015193+00:00 app[worker.1]: Replying to a comment made by muktastrot who said  : महाराष्ट्रीयन at the start
2022-01-04T06:54:41.546901+00:00 app[worker.1]: Replying to a comment made by muktastrot who said  : at the end maharashtrian
2022-01-04T07:05:16.023170+00:00 app[worker.1]: Replying to a comment made by muktastrot who said  : maharashtrian at start
```
a comment made as `at the end महाराष्ट्रीयन` was not detected by the bot. other 3 combinations were detected successfully and replied to as shown in above log.

**Comment by vinodnimbalkar** [comment]
> कळलं. ते \b, ^, \s नक्की काय करतात सांगू शकतो का? किंवा त्यांची मदत कुठे वाचता येईल त्याची दुवा देऊ शकतो का? मी वाचून समजायचा प्रयत्न करतो.

https://docs.python.org/3/library/re.html

`^` हा कोणत्याही वाक्याच्या सुरवातीला शब्द शोधण्याचा प्रयत्न करतो.  `\s` म्हणजे रिकामी जागा अर्थात स्पेस. जर शब्दाच्या सुरवातीला उदा . **\sमहाराष्ट्रीयन** वापरला असेल तर रेगुलर एक्सप्रेशन शब्द शोधताना त्या शब्दाच्या सुरवातीला एक रिकामी जागा आहे का ते पाहतो, तसेच जर `\s` शब्दाच्या शेवटी उदा. **महाराष्ट्रीयन\s** वापरला असेल तर रेगुलर एक्सप्रेशन तो शब्द शोधून त्या शब्दाला लागून लगेच एक रिकामी जागा आहे का ते पाहतो, `\s` शब्दाच्या आधी आणि नंतर असेल उदा. \sमहाराष्ट्रीयन\s तर त्या शब्दाच्या आधी आणि नंतर एक रिकामी जागा आहे का हे पाहतो, उदा. तो **महाराष्ट्रीयन** आहे. उदाहणामध्ये दिल्याप्रमाणे `तो` नंतर एक रिकामी जागा आहे म्हणजेच **महाराष्ट्रीयन** शब्दाच्या आधी एक रिकामी जागा आहे, त्याचप्रमाणे **महाराष्ट्रीयन** आणि `आहे` मध्ये एक रिकामी जागा आहे, म्हणजेच **महाराष्ट्रयीन** नंतर एक रिकामी ज़ागा आहे. 

> a comment made as at the end महाराष्ट्रीयन was not detected by the bot. other 3 combinations were detected successfully and replied to as shown in above log.

Oops! Add one `|` and `\sमहाराष्ट्रीयन` an existing one, we've to write all possible combinations to detect the word.

**Comment by sanketgarade** [comment]
> Add one | and \sमहाराष्ट्रीयन an existing one, we've to write all possible combinations to detect the word.

चालेल. तुम्हाला कधी वेळ मिळाला तर तुम्ही पण करू शकता. 😊

**Comment by sanketgarade** [comment]
चाचणी यशस्वी 😃
